### ISSUE TITLE
Start time, End time filtering in querying the indices

### ISSUE THREAD

**Issue by HaseebLUMS** [dyn-tracing/trace_storage#38]
Currently the indices query does not cater the start-time and end-time params provided in the user query

**Comment by HaseebLUMS** [comment]
Resolved for Folders Index. 

https://github.com/dyn-tracing/trace_storage/commit/d8c172f2e0e92397541cfa40a093a046e16e46a7

**Comment by HaseebLUMS** [comment]
@jessberg could you please resolve it for Sequence Bloom Trees Index?

**Comment by jessberg** [comment]
Done.
